easy_admin:
    design:
      menu:
        - label: 'Gestion des Produits'
          icon: 'beer'
          children:
            - { entity: 'Product' , label: 'Produit'}
            - { entity: 'Picture' , label: 'Photo'}
    entities:
        Product:
          class: App\Entity\Product

        Picture:
          class: App\Entity\Picture
          form:
            fields:
              - { property: 'product'}
              - { property: 'imageFile', type: 'file', base_path: '%vich_uploader.mappings%'}
