easy_admin:
  site_name: 'Brasserie Osseus'
  design:
    form_theme:
      - '@EasyAdmin/form/bootstrap_4.html.twig'

    menu:
      - label: 'Gestion des Produits'
        icon: 'beer'
        children:
          - { entity: 'Product' , label: 'Produit'}
          - { entity: 'Picture' , label: 'Photo'}
      - label: 'Gestion des utilisateurs'
        icon: 'user'
        children:
          - { entity: 'User', label: 'Utilisateur' }
  entities:
    Product:
      class: App\Entity\Product

    Picture:
      class: App\Entity\Picture
      list:
        fields:
          - { property: 'id' }
          - { property: 'filename', type: 'image', base_path: '%vich_map%'}
      show:
        fields:
          - { property: 'filename', type: 'image', base_path: '%vich_map%'}
      form:
        fields:
          - { property: 'imageFile', type: 'vich_image' }
    User:
      class: App\Entity\User
      controller: App\Controller\UserController
      list:
        fields: ['id', 'username', 'roles']
      form:
        fields:
          - { property: 'username'}
          - { property: 'password', type: 'password'}
          - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'Utilisateur': 'ROLE_USER', 'Admin': 'ROLE_ADMIN'} } }

