# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"

    filter_sets:
        my_thumb:
            filters:
                thumbnail:
                  quality: 100
                  size: [500,500]
                  mode: outbound
        my_medium:
            filters:
                thumbnail:
                  quality;: 100
                  size: [300,300]

        my_icon2:
          quality: 75
          filters:
            thumbnail: { size: [80,80], mode: outbound }



