vich_uploader:
    db_driver: orm

#    mappings:
#        product_image:
#            uri_prefix: /media/products
#            upload_destination: '%kernel.project_dir%/public/media/products'
#            namer: Vich\UploaderBundle\Naming\UniqidNamer

    mappings:
        product_image:
            uri_prefix:         '%vich_map%'
            upload_destination: '%kernel.project_dir%/public%vich_map%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
